---
abstract: 'trace who is calling accessors'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Method-Debug
provides:
  Class::Method::Debug:
    file: lib/Class/Method/Debug.pm
    version: 1.100690
requires:
  Class::Method::Modifiers: 0
  Devel::StackTrace: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  perl: 5.008
resources:
  repository: http://github.com/hanekomu/Class-Method-Debug
version: 1.100690
